
#################################################################
- alias: 'Alan Away'
  condition:
    - condition: state
      entity_id: input_boolean.alanhome
      state: 'on'
    - condition: template
      value_template: >
        {%- if states.input_boolean.alanhome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.alanhome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.alandtse_nexus5, device_tracker.nexus_5
      state: 'not_home'
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.alanhome
    - service: logbook.log
      data_template:
        name: "Alan away: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Away.
          {%- endfor -%}

- alias: 'Ray Away'
  condition:
    - condition: state
      entity_id: input_boolean.rayhome
      state: 'on'
    - condition: template
      value_template: >
        {%- if states.input_boolean.rayhome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.rayhome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.raywtse_note4, device_tracker.ray_tse_galaxy_note4
      state: 'not_home'
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.rayhome
    - service: logbook.log
      data_template:
        name: "Ray away: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Away.
          {%- endfor -%}

- alias: 'Alan Home'
  condition:
    - condition: state
      entity_id: input_boolean.alanhome
      state: 'off'
    - condition: template
      value_template: >
        {%- if states.input_boolean.alanhome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.alanhome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.alandtse_nexus5, device_tracker.nexus_5
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.alanhome
    - service: logbook.log
      data_template:
        name: "Alan home: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Home.
          {%- endfor -%}

- alias: 'Ray Home'
  condition:
    - condition: state
      entity_id: input_boolean.rayhome
      state: 'off'
    - condition: template
      value_template: >
        {%- if states.input_boolean.rayhome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.rayhome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.raywtse_note4, device_tracker.ray_tse_galaxy_note4
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.rayhome
    - service: logbook.log
      data_template:
        name: "Ray home: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Home.
          {%- endfor -%}
#### Guests

- alias: 'Solomon Away'
  condition:
    - condition: state
      entity_id: input_boolean.solomonhome
      state: 'on'
    - condition: template
      value_template: >
        {%- if states.input_boolean.solomonhome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.solomonhome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.70480f72bc9b
      state: 'not_home'
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.solomonhome
    - service: logbook.log
      data_template:
        name: "Solomon away: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Away.
          {%- endfor -%}
- alias: 'Solomon Home'
  condition:
    - condition: state
      entity_id: input_boolean.solomonhome
      state: 'off'
    - condition: template
      value_template: >
        {%- if states.input_boolean.solomonhome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.solomonhome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.70480f72bc9b
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.solomonhome
    - service: logbook.log
      data_template:
        name: "Solomon home: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Home.
          {%- endfor -%}

- alias: 'Orla Away'
  condition:
    - condition: state
      entity_id: input_boolean.orlahome
      state: 'on'
    - condition: template
      value_template: >
        {%- if states.input_boolean.orlahome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.orlahome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.78fd940d9949
      state: 'not_home'
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.orlahome
    - service: logbook.log
      data_template:
        name: "Orla away: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Away.
          {%- endfor -%}
- alias: 'Orla Home'
  condition:
    - condition: state
      entity_id: input_boolean.orlahome
      state: 'off'
    - condition: template
      value_template: >
        {%- if states.input_boolean.orlahome.last_changed -%}
          {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.orlahome.last_changed)) > 300 }}
        {%- else -%}
          true
        {%- endif -%}
  trigger:
    - platform: state
      entity_id: device_tracker.78fd940d9949
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.orlahome
    - service: logbook.log
      data_template:
        name: "Orla home: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is Home.
          {%- endfor -%}

- alias: 'Mark both away if Abode armed'
  condition:
   - condition: or
     conditions:
      - condition: state
        entity_id: input_boolean.rayhome
        state: 'on'
      - condition: state
        entity_id: input_boolean.alanhome
        state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.abodestatus
      state: 'away'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.rayhome
    - service: homeassistant.turn_off
      entity_id: input_boolean.alanhome
    - service: homeassistant.turn_off
      entity_id: input_boolean.solomonhome
    - service: homeassistant.turn_off
      entity_id: input_boolean.orlahome

#################################################################
## Security System
#################################################################

- alias: 'Disarm Abode from Away'
  condition:
    condition: state
    entity_id: input_select.abodestatus
    state: 'away'
  trigger:
   - platform: state
     entity_id: group.household
     state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.abodestandby

- alias: 'Garage door left open'
  condition:
    condition: and
    conditions: 
      - condition: template
        value_template: >
          {%- if states.cover.garage_door_opener.last_changed -%}
            {{ (as_timestamp(now()) - as_timestamp(states.cover.garage_door_opener.last_changed)) > 1 }}
          {%- else -%}
            true
          {%- endif -%}
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.abodestatus
          state: 'home'
        - condition: state
          entity_id: input_select.abodestatus
          state: 'away'
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    state: 'open'
  action:
    - service: script.notificationgaragedoor 

- alias: 'Disarm Abode at night'
  condition:
    condition: state
    entity_id: input_select.abodestatus
    state: 'home'
  trigger:
   - platform: state
     entity_id: input_boolean.rayhome, input_boolean.alanhome
     to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.abodestandby

- alias: 'Abode Home from Standby'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: input_select.abodestatus
       state: 'standby'
     - condition: time
       after: '21:15:00'
       before: '07:30:00'
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
     - condition: template
       value_template: >
         {%- if states.input_select.abodestatus.last_changed -%}
           {{ (as_timestamp(now()) - as_timestamp(states.input_select.abodestatus.last_changed)) > 300 }}
         {%- else -%}
           true
         {%- endif -%}
  trigger:
   - platform: time
     minutes: '/10'
     seconds: 00
  action:
     service: homeassistant.turn_on
     entity_id: script.abodehome

- alias: 'Abode Standby'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: group.household
       state: 'on'
     - condition: time
       after: '08:15:00'
       before: '19:45:00'
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
     - condition: template
       value_template: >
         {%- if states.input_select.abodestatus.last_changed -%}
           {{ (as_timestamp(now()) - as_timestamp(states.input_select.abodestatus.last_changed)) > 300 }}
         {%- else -%}
           true
         {%- endif -%}
     - condition: or
       conditions:
        - condition: state
          entity_id: input_select.abodestatus
          state: 'home'
        - condition: state
          entity_id: input_select.abodestatus
          state: 'away'
  trigger:
   - platform: time
     minutes: '/10'
     seconds: 00
  action:
     service: homeassistant.turn_on
     entity_id: script.abodestandby

#- alias: 'Adjust settings changed by Abode'
#  condition:
#    condition: and
#    conditions:
#     - condition: or
#       conditions:
#        - condition: state
#          entity_id: input_select.abodestatus
#          state: 'home'
#        - condition: state
#          entity_id: input_select.abodestatus
#          state: 'standby'
#     - condition: or
#       conditions:
#        - condition: state
#          entity_id: input_boolean.thermo_away_main
#          state: 'on'
#        - condition: state
#          entity_id: input_boolean.thermo_away_upstairs
#          state: 'on'
#  trigger:
#   - platform: time
#     minutes: '/10'
#     seconds: 00
#  action:
   #  - service: climate.set_away_mode
   #    data:
   #      entity_id: climate.downstairs
   #      away_mode: 'False'
   #  - service: climate.set_away_mode
   #    data:
   #      entity_id: climate.upstairs
   #      away_mode: 'False'

- alias: 'Arm Abode'
  condition:
    condition: state
    entity_id: input_boolean.abodeupdate
    state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      state: 'off'
  action:
     service: homeassistant.turn_on
     entity_id: script.abodeaway

- alias: 'Abode Home at night'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
     - condition: state
       entity_id: group.household
       state: 'on'
  trigger:
    platform: time
    after: '20:00:00'
  action:
     service: homeassistant.turn_on
     entity_id: script.abodehome

- alias: 'Disarm Abode in the morning'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: group.household
       state: 'on'
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
  trigger:
    platform: time
    after: '07:45:00'
  action:
     service: homeassistant.turn_on
     entity_id: script.abodestandby

#################################################################
## HASS Related
#################################################################


- alias: "Update Available Notification"
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.pushbullet
      data:
        message: "HomeAssistant {{ states('updater.updater') }} is now available"
        title: "Update HASS"
        target: device/Nexus5
    - service: persistent_notification.create
      data:
        title: "Update Available"
        message: >
          Home Assistant {{ states('updater.updater') }} is available, please [update](https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/#upgrading).
        notification_id: "update_available"

#################################################################
## Commute Times
#################################################################

- alias: "Morning Commute"
  condition:
    condition: and
    conditions:
     - condition: time
       after: '08:15:00'
       before: '11:00:00'
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
     - condition: state
       entity_id: input_boolean.alanhome
       state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.morning_commute
    below: 25 
  action:
    - service: notify.pushbullet
      data:
        message: Commute time is 25 minutes
        title: Leave for Work
        target: device/Nexus5
    - service: homeassistant.turn_on
      entity_id: script.notificationleavework

- alias: "Evening Commute"
  condition:
    condition: and
    conditions:
     - condition: time
       after: '17:00:00'
       before: '20:00:00'
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
     - condition: state
       entity_id: input_boolean.alanhome
       state: 'off'
  trigger:
    platform: numeric_state
    entity_id: sensor.evening_commute
    below: 25
  action:
    service: notify.pushbullet
    data:
      message: Commute time is 25 minutes
      title: Leave for Home
      target: device/Nexus5

- alias: "Plex Spy notification"
  trigger:
    platform: state
    entity_id: sensor.plexspy
  action:
   # - service: notify.pushbullet
   #   data_template:
   #     message: >
   #       {%- if states.sensor.plexspy.attributes -%}
   #         {% set space = joiner(' ') %}
   #         {%- for attr in states.sensor.plexspy.attributes -%}
   #          {%- if not attr=="friendly_name" and not attr=="unit_of_measurement" -%}
   #           {{space()}}{{attr}} is watching {{states.sensor.plexspy.attributes[attr]}}.
   #          {%- endif -%}
   #         {%- endfor -%}
   #       {%- endif -%}
   #     title: "Plex {{ trigger.to_state.state }} people streaming. "
   #     target: device/myiPhone
   # - service: logbook.log
   #   data_template:
   #     name: "Plex {{ trigger.to_state.state }} people streaming. "
   #     message: >
   #       {%- if states.sensor.plexspy.attributes -%}
   #         {% set space = joiner(' ') %}
   #         {%- for attr in states.sensor.plexspy.attributes -%}
   #          {%- if not attr=="friendly_name" and not attr=="unit_of_measurement" -%}
   #           {{space()}}{{attr}} is watching {{states.sensor.plexspy.attributes[attr]}}.
   #          {%- endif -%}
   #         {%- endfor -%}
   #       {%- endif -%}
#
#################################################################
## Home Automation Related
#################################################################

- alias: 'Open Garage door when someone home'
  condition:
   - condition: state
     entity_id: cover.garage_door_opener 
     state: 'closed'
   - condition: state
     entity_id: input_boolean.abodeupdate
     state: 'on'
   - condition: template
     value_template: >
       {%- if states.cover.garage_door_opener.last_changed -%}
         {{ (as_timestamp(now()) - as_timestamp(states.cover.garage_door_opener.last_changed)) > 300 }}
       {%- else -%}
         true
       {%- endif -%}
   - condition: template
     value_template: >
       {%- if states.automation.open_garage_door_when_someone_home.last_triggered -%}
         {{ (as_timestamp(now()) - as_timestamp(states.automation.open_garage_door_when_someone_home.last_triggered)) > 150 }}
       {%- else -%}
         true
       {%- endif -%}
  trigger:
   - platform: state
     entity_id: input_boolean.alanhome, input_boolean.rayhome
     from: 'off'
     to: 'on'
   - platform: zone
     entity_id: device_tracker.00254270079f, device_tracker.raywtse_note4, device_tracker.alandtse_nexus5
     zone: zone.home
     event: enter
  action:
    #- service: cover.open_cover 
    #  entity_id: cover.garage_door_opener 
    - service: notify.pushbullet
      data:
        message: "Should open garage door" 
- alias: 'Close garage door when Abode is Home or Away'
  condition:
 #  - condition: state
 #    entity_id: cover.garage_door_opener
 #    state: 'open'
 #    for:
 #     minutes: 10
   - condition: template
     value_template: >
       {%- if states.automation.close_garage_door_when_abode_is_home_or_away.attributes.last_triggered  -%}
         {{(as_timestamp(now()) - as_timestamp(states.automation.close_garage_door_when_abode_is_home_or_away.attributes.last_triggered)) > 60}}
       {%- else -%}
         true
       {%- endif -%}
   - condition: or
     conditions:
      - condition: state
        entity_id: input_select.abodestatus
        state: 'home'
      - condition: state
        entity_id: input_select.abodestatus
        state: 'away'
  trigger:
   - platform: state
     entity_id: cover.garage_door_opener
     state: 'open'
     for: 
       minutes: 5
  action:
    - service: script.notificationgaragedoor
- alias: "Owntracks Refresh"
  condition:
   - condition: state
     entity_id: input_boolean.alanhome
     state: 'off'
   - condition: state
     entity_id: input_boolean.rayhome
     state: 'off'
  trigger:
    - platform: time
      minutes: '/15'
      seconds: 0
  action:
    service: script.owntracks_update

