- platform: mqtt
  state_topic: 'camera/DCS-2330L/motion'
  friendly_name: "Kids' Room Motion" 
  name: 'dcs-2330l_motion'
  device_class: motion
  # inactive: No alarm
  # active: Motion Detected
  value_template: >-
          {%- if value != "inactive" %}
              ON
          {% else %}
              OFF
          {%- endif %}
- platform: doorbird
- platform: template
  sensors:
    doorbell:
      friendly_name: Gate Doorbell
      device_class: sound
      value_template: 'off'
      entity_id: foo.bar
    frontdoor_motion:
      friendly_name: Gate Motion
      device_class: motion
      value_template: 'off'
      entity_id: foo.bar
    frontdoor_open:
      friendly_name: Gate Unlocked
      value_template: 'off'
      entity_id: foo.bar
    greatroomswitch_motion:
      friendly_name: Great Room Switch Motion
      device_class: motion
      entity_id:
        - sensor.great_room_switch_burglar 
      value_template: >-
        {{states("sensor.great_room_switch_burglar") |float > 0 }}
- platform: simplisaferf
