- platform: mqtt
  state_topic: 'camera/DCS-2330L/motion'
  name: "Kids' Room Motion"
  device_class: motion
  # inactive: No alarm
  # active: Motion Detected
  value_template: >-
          {%- if value != "inactive" %}
              ON
          {% else %}
              OFF
          {%- endif %}
- platform: mqtt
  state_topic: 'camera/garage/motion'
  name: "Garage Camera Motion"
  device_class: motion
  # inactive: No alarm
  # active: Motion Detected
  value_template: >-
          {%- if value != "inactive" %}
              ON
          {% else %}
              OFF
          {%- endif %}
- platform: template
  sensors:
    doorbell:
      friendly_name: Gate Doorbell
      device_class: sound
      value_template: 'off'
    gate_motion:
      friendly_name: Gate Motion
      device_class: motion
      value_template: 'off'
    gate_unlocked:
      friendly_name: Gate Unlocked
      value_template: 'off'
    gate_open:
      friendly_name: Gate 
      device_class: opening
      value_template: >-
        {{((states("sensor.gate_alarm_level") |float > 0) and (states("sensor.gate_alarm_level") |float < 254) or (states("sensor.gate_alarm_level") | float == 255) and (states("sensor.gate_access_control") | float == 22))}}
    garage:
      friendly_name: Garage
      device_class: opening
      value_template: >-
        {{is_state("cover.garage_door_opener","open")}}
    nookswitch_motion:
      friendly_name: Nook Switch Motion
      device_class: motion
      value_template: >-
        {{(states("sensor.nook_switch_burglar") |float > 0) and (states("sensor.nook_switch_burglar") |float < 254 )}}
    guestroomswitch_motion:
      friendly_name: Guest Room Switch Motion
      device_class: motion
      value_template: >-
        {{(states("sensor.guest_room_switch_burglar") |float > 0) and (states("sensor.guest_room_switch_burglar") |float < 254)}}
    greatroomswitch_motion:
      friendly_name: Great Room Switch Motion
      device_class: motion
      value_template: >-
        {{(states("sensor.great_room_switch_burglar") |float > 0) and (states("sensor.great_room_switch_burglar") |float < 254)}}
    guesthallswitch_motion:
      friendly_name: Guest Hall Switch Motion
      device_class: motion
      value_template: >-
        {{(states("sensor.guest_hall_switch_burglar") |float > 0) and (states("sensor.guest_hall_switch_burglar") |float < 254)}}
    garageswitch_motion:
      friendly_name: Garage Switch Motion
      device_class: motion
      value_template: >-
        {{(states("sensor.garage_burglar") |float > 0) and (states("sensor.garage_burglar") |float < 254)}}
    tv:
      friendly_name: TV 
      device_class: occupancy
      value_template: >-
        {{is_state('switch.hdmi_0', 'on')}}
    office_computer:
      friendly_name: Office Computer
      device_class: occupancy
      value_template: >-
        {{is_state("device_tracker.38d547084a5e","home")}}
- platform: simplisaferf
