homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_home
  longitude: !secret long_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 65
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
# Show links to resources in log and frontend
#introduction:

zone:
 - name: home
   latitude: !secret lat_home
   longitude: !secret long_home
   radius: 50
   icon: mdi:home
 - name: work
   latitude: !secret lat_work
   longitude: !secret long_work
   radius: 150
   icon: mdi:briefcase
 - name: Grandparent's Irvine
   latitude: !secret lat_grandparents
   longitude: !secret long_grandparents
   radius: 50
   icon: mdi:home
 - name: Grandparent's San Diego
   latitude: !secret lat_grandparents2
   longitude: !secret long_grandparents2
   radius: 50
   icon: mdi:home
 - name: Han's
   latitude: !secret lat_grandparents
   longitude: !secret long_grandparents
   radius: 50
   icon: mdi:home
# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url 
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key 
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - axis

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
#Adds Amazon Echo support
emulated_hue:
  expose_by_default: false
# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time__date
      - sensor.great_room_switch_sourcenodeid
      - sensor.great_room_switch_sourcenodeid_2
      - sensor.great_room_switch_alarm_level
      - sensor.great_room_switch_alarm_level_2
      - sensor.great_room_switch_alarm_type
      - sensor.great_room_switch_alarm_type_2

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: critical
    homeassistant.components.roku: debug
    homeassistant.components.zwave.util: info
    custom_components.media_player.alexa: debug
    custom_components.device_tracker.bluetooth_tracker: critical
    custom_components.device_tracker.ddwrt: critical
    homeassistant.core: error
    homeassistant.components.mqtt: warning
    homeassistant.components.sensor.template: error
    homeassistant.components.configurator: info
# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300
media_player:
#  - platform: tts_bluetooth_speaker
#    address:
#      - 84:D6:D0:21:85:21.a2dp_sink
#      - 00:FC:8B:D5:99:F3.a2dp_sink
#    volume: 1.00
#    pre_silence_duration: .5
#    connect_script: /home/homeassistant/.homeassistant/scripts/connect_bluetooth.sh
#    disconnect_script: /home/homeassistant/.homeassistant/scripts/disconnect_bluetooth.sh
#    cache_dir: /home/homeassistant/.homeassistant/tts
  - platform: alexa
    email: !secret amazon_user
    password: !secret amazon_pass
    url: amazon.com
#remote:
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: ecobee
    name: ecobee
  - platform: html5
    name: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
# Lily Camera
camera:
  - platform: mjpeg
    name: Kids Room
    username: !secret dlink_user
    password: !secret dlink_password
    still_image_url: http://DCS-2330L:8080/dmsdump?nowprofileid=1
    mjpeg_url: http://dcs-2330l:8080/video1.mjpg
  - platform: mjpeg
    name: Doorbird
    username: !secret doorbird_user
    password: !secret doorbird_password
    still_image_url: http://bha-1ccae3707f56/bha-api/image.cgi
    mjpeg_url: http://bha-1ccae3707f56/bha-api/video.cgi
  - platform: mjpeg
    name: Garage
    still_image_url: !secret garage_still
    mjpeg_url: http://192.168.1.81:8081/ 
  - platform: doorbird
  - platform: mjpeg
    name: Dashcam
    mjpeg_url: http://DR500GW-HD/blackvue_live.cgi?direction=R  
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=SOX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=0.18097826086956523&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=638.6336336336336&centery=236.89189189189187&transx=238.63363363363362&transy=-3.1081081081081265&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24853447&lat=0&lon=0&label=you
    name: Radar
  - platform: generic
    name: Evie Map
    still_image_url: !secret tesla_still_image_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Eva map
    still_image_url: !secret tesla3_eva_still_image_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Grandparents Map
    still_image_url: !secret tesla3_still_image_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Alan Map
    still_image_url: !secret alan_still_image_url 
    limit_refetch_to_url_change: true    
  - platform: generic
    name: Ray Map
    still_image_url: !secret ray_still_image_url
    limit_refetch_to_url_change: true    
cover:
  - platform: myq
    name: garage
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain 
device_tracker:
  - platform: ddwrt
#   Second host is from custom component: https://community.home-assistant.io/t/dd-wrt-dual-band-router-and-multiple-router-support/12000
    hosts: 
      - 192.168.1.1
      - 192.168.1.2
    username: !secret ddwrt_user
    password: !secret ddwrt_password
#   protocol is for custom_component to allow access to second ddwrt
    protocol: ssh
    interval_seconds: 30 
    consider_home: 300
  - platform: owntracks
    max_gps_accuracy: 1000
    interval_seconds: 30 
    consider_home: 300
    waypoints: True
#  - platform: bluetooth_le_tracker
#    interval_seconds: 90
#    consider_home: 300
  - platform: bluetooth_tracker
    interval_seconds: 30
    consider_home: 300
  - platform: nmap_tracker
    hosts:
      - 192.168.1.1/24
      - 192.168.1.2/24
    interval_seconds: 60
    consider_home: 300
   # scan_options: " --privileged -sn -n --host-timeout 10s -T5 "
ecobee:
  api_key: !secret ecobee_key
tesla:
  username: !secret tesla_user
  password: !secret tesla_password
doorbird:
  devices:
    host: bha-1ccae3707f56
#  host: 192.168.1.99
    username: !secret doorbird_user
    password: !secret doorbird_password
    monitored_conditions:
        - doorbell
        - motion
    hass_url_override: https://192.168.1.108:8123
alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_user
  password: !secret simplisafe_password 
recorder:
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - sun
  include:
    domains:
      - sensor
      - input_boolean
      - input_select
      - input_number
wink:
  local_control: true
hdmi_cec:
  devices:
    TV: 0.0.0.0
    RPI: 1.0.0.0
    PS3: 1.1.0.0
shell_command: !include shell_command.yaml
automation: !include_dir_list automations/ 
group: !include groups.yaml
script: !include_dir_merge_named script/
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
intent_script: !include intent_script.yaml
dialogflow: !include apiai.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
switch: !include switch.yaml
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.6/site-packages/python_openzwave/ozw_config/ 
  network_key: !secret zwave_key
