homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_home
  longitude: !secret long_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 65
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
    - type: legacy_api_password
      api_password: !secret api_password


zone:
 - name: home
   latitude: !secret lat_home
   longitude: !secret long_home
   radius: 50
   icon: mdi:home
 - name: work
   latitude: !secret lat_work
   longitude: !secret long_work
   radius: 150
   icon: mdi:briefcase
 - name: Grandparent's Irvine
   latitude: !secret lat_grandparents
   longitude: !secret long_grandparents
   radius: 50
   icon: mdi:home
 - name: Grandparent's San Diego
   latitude: !secret lat_grandparents2
   longitude: !secret long_grandparents2
   radius: 50
   icon: mdi:home
 - name: Han's
   latitude: !secret lat_han
   longitude: !secret long_han
   radius: 50
   icon: mdi:home
# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url 
  #server_port: 8123
  #ssl_certificate: !secret ssl_certificate 
  #ssl_key: !secret ssl_key 

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - axis

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
#Adds Amazon Echo support
emulated_hue:
  expose_by_default: false
# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time_date
      - sensor.great_room_switch_sourcenodeid
      - sensor.great_room_switch_sourcenodeid_2
      - sensor.great_room_switch_alarm_level
      - sensor.great_room_switch_alarm_level_2
      - sensor.great_room_switch_alarm_type
      - sensor.great_room_switch_alarm_type_2
      - automation.battery_sensor_from_attributes
      - automation.update_battery_status_group_members
      - automation.battery_notification
      - automation.battery_notification_clear

logger:
  default: info
  logs:
    homeassistant.components.websocket_api: critical
    homeassistant.components.doorbird: info
    homeassistant.components.zwave.util: info
    custom_components.tesla: debug
    custom_components.alexa_media: debug
    homeassistant.core: info
    homeassistant.components.mqtt: warning
    homeassistant.components.sensor.template: error
    homeassistant.components.configurator: info
    alexapy: debug
    # teslajsonpy: debug
# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google_translate
#    service_name: google_say
#    cache: true
#    cache_dir: /home/homeassistant/.homeassistant/tts
#    time_memory: 300
media_player:
#  - platform: tts_bluetooth_speaker
#    address:
#      - 84:D6:D0:21:85:21.a2dp_sink
#      - 00:FC:8B:D5:99:F3.a2dp_sink
#    volume: 1.00
#    pre_silence_duration: .5
#    connect_script: /home/homeassistant/.homeassistant/scripts/connect_bluetooth.sh
#    disconnect_script: /home/homeassistant/.homeassistant/scripts/disconnect_bluetooth.sh
#    cache_dir: /home/homeassistant/.homeassistant/tts

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_pass
      url: amazon.com
      debug: True
      exclude_devices:
        - "Alan's Alexa Apps"
        - "Solomon's Alexa Apps"
        - Garage
        - "This Device"
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
    #gcm_api_key: !secret gcm_api_key
    #gcm_sender_id: !secret gcm_sender_id
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
# Lily Camera
camera:
  - platform: mjpeg
    name: Kids Room
    username: !secret dlink_user
    password: !secret dlink_password
    still_image_url: http://DCS-2330L.local:8080/dmsdump?nowprofileid=1
    mjpeg_url: http://dcs-2330l.local:8080/video1.mjpg
  - platform: mjpeg
    name: Doorbird
    username: !secret doorbird_user
    password: !secret doorbird_password
    still_image_url: http://bha-1ccae3707f56.local/bha-api/image.cgi
    mjpeg_url: http://192.168.1.99/bha-api/video.cgi
  - platform: mjpeg
    name: Garage
    still_image_url: !secret garage_still
    mjpeg_url: http://192.168.1.81:8081/ 
  - platform: doorbird
  - platform: mjpeg
    name: Dashcam
    mjpeg_url: http://DR500GW-HD.local/blackvue_live.cgi?direction=R  
  - platform: generic
    name: Great Room
    username: !secret dafang_user
    password: !secret dafang_pass
    authentication: basic
    still_image_url: https://dafang.local/cgi-bin/currentpic.cgi
    verify_ssl: false
    scan_interval: 1
    #input: -rtsp_transport tcp -i rtsp://dafang:8554/unicast -an -max_muxing_queue_size 1024 -acodec copy
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=SOX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=0.18097826086956523&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=638.6336336336336&centery=236.89189189189187&transx=238.63363363363362&transy=-3.1081081081081265&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24853447&lat=0&lon=0&label=you
    name: Radar
  - platform: generic
    name: Evie Map
    still_image_url: !secret tesla_still_image_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Eva map
    still_image_url: !secret tesla3_eva_still_image_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Grandparents Map
    still_image_url: !secret tesla3_still_image_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Alan Map
    still_image_url: !secret alan_still_image_url 
    limit_refetch_to_url_change: true    
  - platform: generic
    name: Ray Map
    still_image_url: !secret ray_still_image_url
    limit_refetch_to_url_change: true    
cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain 
device_tracker:
  - platform: ddwrt
#   Second host is from custom component: https://community.home-assistant.io/t/dd-wrt-dual-band-router-and-multiple-router-support/12000
    host: 192.168.1.1
    #- 192.168.1.1
        #     - 192.168.1.2
    username: !secret ddwrt_user
    password: !secret ddwrt_password
    interval_seconds: 30 
    consider_home: 300
#  - platform: bluetooth_le_tracker
#    interval_seconds: 90
#    consider_home: 300
  - platform: bluetooth_tracker
    interval_seconds: 30
    consider_home: 300
  - platform: nmap_tracker
    hosts:
      - 192.168.1.1/24
      - 192.168.1.2/24
    interval_seconds: 60
    consider_home: 300
    exclude:
      - 192.168.1.84
      - 192.168.1.108
#    scan_options: " --privileged -sn -n --host-timeout 10s -T5 "
owntracks:
  max_gps_accuracy: 1000
  interval_seconds: 30
  consider_home: 300
  #tesla:
  #  username: !secret tesla_user
  #  password: !secret tesla_password
doorbird:
  devices:
    host: 192.168.1.99
#  host: 192.168.1.99
    username: !secret doorbird_user
    password: !secret doorbird_password
    events:
        - doorbell
        - motion
   # hass_url_override: https://192.168.1.108:8123
    token: !secret doorbird_token 
  #simplisafe:
    # accounts:
    # username: !secret simplisafe_user
    # password: !secret simplisafe_password 
recorder:
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - sun
      - sensor.time_date
  include:
    domains:
      - alarm_control_panel
      - climate
      - cover
      - group
      - binary_sensor
      - switch
      - lock
      - light
      - automation
      - script
      - sensor
      - input_boolean
      - input_select
      - input_number
      - input_text
      - input_datetime
      - device_tracker
      - media_player
      - person
        # influxdb:
        #   host: 127.0.0.1
        #   username: !secret influxdb_user
        #   password: !secret api_password
        #   tags:
        #   instance: prod
        #   source: hass
        #   tags_attributes:
        #  - friendly_name
hdmi_cec:
  devices:
    TV: 0.0.0.0
    RPI: 1.0.0.0
    PS3: 1.1.0.0
shell_command: !include shell_command.yaml
automation: !include_dir_list automations/ 
group: !include groups.yaml
script: !include_dir_merge_named script/
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
intent_script: !include intent_script.yaml
dialogflow: !include apiai.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
switch: !include switch.yaml
#zwave:
#  usb_path: /dev/ttyACM0
#  config_path: /config/ozw_config/ 
#  network_key: !secret zwave_key
panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

    #image_processing:
    #  - platform: tensorflow
    #    scan_interval: 604800
    #    source:
    #    - entity_id: camera.doorbird
    #    - entity_id: camera.doorbird_1_last_motion
    #    - entity_id: camera.garage
    #    - entity_id: camera.kids_room
    #  - entity_id: camera.great_room
    # file_out:
    #   - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
    #  - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    # model:
    #  graph: /home/homeassistant/.homeassistant/tensorflow/frozen_inference_graph.pb
    #  categories:
    #    - category: person
system_health:
stream:
person:
breaking_changes:
pi_hole:
  - host: 'pi.hole'
    api_key: !secret pi_hole_api_key
sentry:
  dsn: !secret sentry_dsn
