homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_home
  longitude: !secret long_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 65
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
# Show links to resources in log and frontend
#introduction:

zone:
 - name: home
   latitude: !secret lat_home
   longitude: !secret long_home
   radius: 50
   icon: mdi:home
 - name: work
   latitude: !secret lat_work
   longitude: !secret long_work
   radius: 150
   icon: mdi:briefcase
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url 
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key 
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - axis

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
#Adds Amazon Echo support
emulated_hue:
  expose_by_default: false
# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
logger:
# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: ecobee
    name: ecobee
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password
# Lily Camera
camera:
  - platform: mjpeg
    name: kidsroom
    username: !secret dlink_user
    password: !secret dlink_password
    still_image_url: http://DCS-2330L:8080/dmsdump?nowprofileid=1
    mjpeg_url: http://dcs-2330l:8080/video1.mjpg
  - platform: mjpeg
    name: Doorbird
    username: !secret doorbird_user
    password: !secret doorbird_password
    still_image_url: http://bha-1ccae3707f56/bha-api/image.cgi
    mjpeg_url: http://bha-1ccae3707f56/bha-api/video.cgi
  - platform: doorbird
    last_visitor: true
  - platform: mjpeg
    name: dashcam
    mjpeg_url: http://DR500GW-HD/blackvue_live.cgi?direction=R  
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=SOX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=0.18097826086956523&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=638.6336336336336&centery=236.89189189189187&transx=238.63363363363362&transy=-3.1081081081081265&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24853447&lat=0&lon=0&label=you
    name: Radar
  - platform: generic
    name: Tesla Map
    still_image_url: !secret tesla_still_image_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Alan Map
    still_image_url: !secret alan_still_image_url 
    limit_refetch_to_url_change: true    
  - platform: generic
    name: Ray Map
    still_image_url: !secret ray_still_image_url
    limit_refetch_to_url_change: true    
cover:
  - platform: myq
    name: garage
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain 
device_tracker:
  - platform: ddwrt
#   Second host is from custom component: https://community.home-assistant.io/t/dd-wrt-dual-band-router-and-multiple-router-support/12000
    hosts: 
      - 192.168.1.1
      - 192.168.1.2
    username: !secret ddwrt_user
    password: !secret ddwrt_password
#   protocol is for custom_component to allow access to second ddwrt
    protocol: ssh
    interval_seconds: 30 
    consider_home: 300
  - platform: owntracks
    max_gps_accuracy: 1000
    interval_seconds: 30 
    consider_home: 300
    waypoints: True
#  - platform: bluetooth_le_tracker
#    interval_seconds: 90
#    consider_home: 300
  - platform: bluetooth_tracker
    interval_seconds: 30
    consider_home: 300
  - platform: nmap_tracker
    hosts:
      - 192.168.1.1/24
      - 192.168.1.2/24
    interval_seconds: 60
    consider_home: 300
   # scan_options: " --privileged -sn -n --host-timeout 10s -T5 "
ecobee:
  api_key: !secret ecobee_key
tesla:
  username: !secret tesla_user
  password: !secret tesla_password
doorbird:
  host: bha-1ccae3707f56  
#  host: 192.168.1.99
  username: !secret doorbird_user
  password: !secret doorbird_password

alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_user
  password: !secret simplisafe_password 
recorder:
  purge_days: 3
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - sun

shell_command: !include shell_command.yaml
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
intent_script: !include intent_script.yaml
apiai: !include apiai.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
switch: !include switch.yaml
