  alias: 'Adjust ecobee settings changed by Abode'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
     - condition: or
       conditions:
        - condition: state
          entity_id: input_select.abodestatus
          state: 'home'
        - condition: state
          entity_id: input_select.abodestatus
          state: 'standby'
     - condition: or
       conditions:
        - condition: state
          entity_id: input_boolean.thermo_away_main
          state: 'on'
        - condition: state
          entity_id: input_boolean.thermo_away_upstairs
          state: 'on'
  trigger:
   - platform: state
     entity_id: group.downstairs_occupancy, group.upstairs_occupancy
     from: 'off'
     to: 'on'
  action:
    - service: logbook.log
      data_template:
        name: "Ecobee home: "
        message: >-
          {%- for state in states if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} is enabled.
          {%- endfor -%}
    - service: climate.set_away_mode
      data_template:
        entity_id: >
          {% if trigger.entity_id == "group.downstairs_occupancy" %} climate.downstairs
          {% elif trigger.entity_id == "group.upstairs_occupancy" %} climate.upstairs
          {% endif %}
        away_mode: 'False'
    - service: climate.set_hold_mode
      data_template:
        entity_id: >
          {% if trigger.entity_id == "group.downstairs_occupancy" %} climate.downstairs
          {% elif trigger.entity_id == "group.upstairs_occupancy" %} climate.upstairs
          {% endif %}
        hold_mode: 'None'
